version: '3.5'
# Network
networks:
  sabre:
      driver: bridge
services:
  sabre_dav:
    restart: always
    build: .
    environment:
      - ENABLE_XDEBUG=1
      - XDEBUG_CONFIG=remote_host=172.24.0.1 # this is gateway address in network docker 
    env_file: ./src/.env
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
    depends_on:
      - mysql_db
    networks:
      - sabre  
  # database
  mysql_db:
    image: mysql:5.7.12
    restart: always
    env_file: ./src/.env
    ports:
        - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    networks:
      - sabre
  # admin for mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9099:8080
    networks:
      - sabre