version: '3.5'
# Network
networks:
  sabre:
      driver: bridge
services:
  sabre_dav:
    restart: always
    build: .
    environment:
      - ENABLE_XDEBUG=1
      # Linux kernel client_host=host.docker.internal
      # Other kernel client_host=172.24.0.1 `docker network  inspect [name]` is gateway address in network docker 
      - XDEBUG_CONFIG=client_host=host.docker.internal
    env_file: ./src/.env
    ports:
      - "80:80"
    volumes:
      - "./src:/var/www/html"
    networks:
      - sabre  
  # admin for mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 9099:8080
    networks:
      - sabre